#####################################
#
#   Moneta -- Spring Boot deployment
#
#	Exposed ports:		8080 
#	Exposed Volumes:
#		/config		Expected to contain moneta.xml, logback.xml, and optionally application.properties
#		/lib		Expected to contain additional jars needed (e.g. JDBC drivers)
#		/logs		Expected log file output (optional - logback.xml)
#
#		Note:  Containers containing relational databases required by your configuration should be linked.
#
#		Sample usage:
#
#		docker image springboot .
#       docker run -d -p 8080:8080 -p 8081:8081 \ 
#			-v /c/Users/moneta/springboot/config:/config \ 
#			-v /c/Users/moneta/springboot/logs:/logs \ 
#			-v /c/Users/moneta/springboot/jarlib:/jarlib \ 
#			springboot
#

FROM java:7-jre

MAINTAINER Derek C. Ashmore

#  External volume definitions
RUN mkdir /jarlib
VOLUME /jarlib
RUN mkdir /config
VOLUME /config
RUN mkdir /logs
VOLUME /logs

ENV MONETA_URL https://github.com/Derek-Ashmore/moneta/releases/download/moneta-#{project.version}/moneta-springboot-#{project.version}.jar
RUN curl -SL "$MONETA_URL" -o moneta-springboot.jar

ENV CLASSPATH /config:/jarlib/*.jar:moneta-springboot.jar

EXPOSE 8080

ENTRYPOINT ["java", "-classpath", "$CLASSPATH", "-jar", "moneta-springboot.jar"]